Add a FLATTEN_RECORD_LIST formula
gristlabs/grist-core pull request #1215
Opened 2024-09-19 13:53 UTC by hexaltation

## Context

Formulas `Carts.lookupRecords(customer=$id).Cart` returns a "list of lists/RecordSet" ([Foods[[1, 2, 3]], Foods[[1]]]) which is not handled properly by Grist when trying to type it as a Reference List.

A fix is to return a flattened list using a list comprehension [el for val in Carts.lookupRecords(customer=$id).Cart for el in val]

## Proposed solution

Add a `FLATTEN_RECORD_LIST(RecordSet, dedup=False)` formula that returns a much more manageable list of `Records`

## Related issues

Fixes #1130

## Has this been tested?

- [ ] 👍 yes, I added tests to the test suite
- [ ] 💭 no, because this PR is a draft and still needs work
- [ ] 🙅 no, because this is not relevant here
- [x] 🙋 no, because I need help

I'm not sure of the best way to test this. Creating a .grist file that verify the formula returns the good result in nbrowser tests or python tests inside the docstring, but how create a proper RecordSet to do unit tests ?

Thanks for your help.

2024-09-23 11:04 UTC, fflorent requested changes
Thanks @hexaltation! Few remarks from my side.

2024-09-23 11:04 UTC, fflorent commented on sandbox/grist/functions/lookup.py
> +        raise TypeError("Unexpected Argument, waiting of a list of Records")
wouldn't `waiting for a list of Records` more English?

2024-09-23 11:04 UTC, fflorent commented on sandbox/grist/functions/lookup.py
> +    if list(el_type)[0] != 'Record':
Why do you have to check the first element only?

Wouldn't `'Record' in el_type` be more robust?

2024-10-07 11:13 UTC, closed without merging

2024-10-07 11:14 UTC, berhalak commented
Closing this one. I'll create new one with option 2 from the issue.