Remove duplicated hide colum option
gristlabs/grist-core pull request #292
Opened 2022-09-27 13:08 UTC by LouisDelbosc

Related issue #290 

The issue has not been checked, maybe there is a reason why you have two same option. Nonetheless, here the fix.

Tell me if you have any comments.

<img width="333" alt="Screenshot 2022-09-27 at 15 06 15" src="https://user-images.githubusercontent.com/11460746/192534484-090159ef-9937-406b-a733-a002098f41c1.png">

2022-09-27 15:02 UTC, berhalak commented
Hi @LouisDelbosc,

Actually, can you remove this option from `ColumnContextMenu` and leave that one in `MultiColumnMenu` (also, the logic for disabling it is missing check if the menu is on `Raw Data View`).
`MultiColumnMenu` is part of `ColumnContextMenu`, so with your change, it would be removed from the menu that is shown when multiple columns are selected.

2022-09-28 10:52 UTC, LouisDelbosc commented
@berhalak thanks for you comment.

Is it more robust like this ?

2022-09-28 21:05 UTC, berhalak requested changes

2022-09-28 21:05 UTC, berhalak commented on app/client/ui/GridViewMenus.ts
> +  const { disableModify, filterOpenFunc, colId, sortSpec, isReadonly } = options;
Looks very good. The only thing is this logic with `isRaw`. `Hide columns` in MultiColumnMenu should be hidden when `isRaw` is set to true. Can you add this logic there?

2022-09-30 15:09 UTC, berhalak approved these changes
Thanks, works great!

2022-09-30 15:34 UTC, merged