Fix drag icon for view layout
gristlabs/grist-core pull request #327
Opened 2022-10-26 09:24 UTC by LouisDelbosc

Related issue #263 

I did what the issues comments suggested.

Here the result:

<img width="304" alt="Screenshot 2022-10-26 at 11 23 21" src="https://user-images.githubusercontent.com/11460746/197989140-85ba6ace-b8c0-402b-991a-685fd0651797.png">

2022-10-26 16:23 UTC, berhalak requested changes

2022-10-26 16:23 UTC, berhalak commented on app/client/components/ViewLayout.ts
> +      cssDragIcon('DragDrop',
```suggestion
      cssDragIcon('DragDrop',
      dom.cls("viewsection_drag_indicator"),
```
Can you add this class, there are some internal tests looking for it.

2022-10-26 16:23 UTC, berhalak commented on app/client/components/ViewLayout.css
> -  z-index: 100;   /* ensure it's above the resizer line, since it's hard to grab otherwise */
You also need to move this line. Right now when you have 2 tables next to each other, it is hard to grab this drag element as the resizer is higher in the stack.

2022-10-27 07:53 UTC, LouisDelbosc commented
Thanks @berhalak for your review. I made the change you requested 👍

2022-10-27 09:07 UTC, merged